// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcF5Pu6xLUAcS26jZ0d4lpLdcILbcMIeE',
    appId: '1:883556325547:web:d38ff343ca1a0aa253ffee',
    messagingSenderId: '883556325547',
    projectId: 'online-nursery-plant-shop',
    authDomain: 'online-nursery-plant-shop.firebaseapp.com',
    storageBucket: 'online-nursery-plant-shop.appspot.com',
    measurementId: 'G-V80JB786KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn6SIy5aeMQglhy6P8P7_Wp6Ja-n3tr7s',
    appId: '1:883556325547:android:7a439cc1ac4d68da53ffee',
    messagingSenderId: '883556325547',
    projectId: 'online-nursery-plant-shop',
    storageBucket: 'online-nursery-plant-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4VkZ8rYNqrCFg9mGHdIVYTgD-xfbGMU8',
    appId: '1:883556325547:ios:a9ddc2d478ef6bb653ffee',
    messagingSenderId: '883556325547',
    projectId: 'online-nursery-plant-shop',
    storageBucket: 'online-nursery-plant-shop.appspot.com',
    iosBundleId: 'com.example.onlineNurseryPlantShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4VkZ8rYNqrCFg9mGHdIVYTgD-xfbGMU8',
    appId: '1:883556325547:ios:a9ddc2d478ef6bb653ffee',
    messagingSenderId: '883556325547',
    projectId: 'online-nursery-plant-shop',
    storageBucket: 'online-nursery-plant-shop.appspot.com',
    iosBundleId: 'com.example.onlineNurseryPlantShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcF5Pu6xLUAcS26jZ0d4lpLdcILbcMIeE',
    appId: '1:883556325547:web:c2d79e723b0ace0f53ffee',
    messagingSenderId: '883556325547',
    projectId: 'online-nursery-plant-shop',
    authDomain: 'online-nursery-plant-shop.firebaseapp.com',
    storageBucket: 'online-nursery-plant-shop.appspot.com',
    measurementId: 'G-M941SWCCJS',
  );
}
